# basic statistics and plot
results: ../data/proteins_w_domains.txt ../data/9606.protein.links.v11.0.txt.gz
	python plot_protein-interaction-vs-domains.py 

.PHONY : clean
clean :
	rm -f ../results/*.csv ../results/*.png